# Generated by Django 5.0.7 on 2024-07-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('your_email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('your_query', models.TextField()),
            ],
        ),
    ]
